export const LOGIN = 'LOGIN'
export const LOGIN_OK = 'LOGIN_OK'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_END = 'LOGIN_END'
export const LOGOUT = 'LOGOUT'
export const AUTH0_LOGIN = 'AUTH0_LOGIN'
